import Head from "next/head";
import Feed from "@/components/Feed/Feed";
import { useContext, useEffect,useState } from "react";
import { AuthContext } from "@/context/Auth";
import { default as Login } from "./login/index";
import LoadingPage from "@/components/LoadingPage";
export default function Home() {
    const { user } = useContext(AuthContext);
    const [showLoader, setShowLoader] = useState(true);
    useEffect(() => {
        setTimeout(() => {
            setShowLoader(false);
        }, 2000);
        clearInterval();
    });
    return (
        <>
            <Head>
                <title>Instagram</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {user?.uid ? (
                <Feed />
            ) : (
                <div>{showLoader ? <LoadingPage /> : <Login />}</div>
            )}
        </>
    );
}
